import type { VocabularyItem } from './types'

export const BALANCED_VOCAB: VocabularyItem = {
  label: 'Tenang / Seimbang / Stabil',
  moodKey: 'Balanced',
  keywords: [
    "tenang", "tenang banget", "santai", "santai tapi produktif", "stabil",
    "stabil banget", "adem", "adem pikiran", "adem banget", "aman",
    "aman banget", "damai", "teratur", "tertata", "terjaga",
    "terkondisi", "pas", "pas banget", "wajar", "normal",
    "rileks", "rileks banget", "tidak panik", "ga panik", "ga terburu-buru",
    "tanpa tekanan", "enjoy", "enjoy banget", "nyaman", "nyaman banget",
    "kondusif", "kondusif banget", "terarah", "jernih", "seimbang",
    "balance", "balanced", "tenang pikiran", "pikiran tenang", "santuy tapi jalan",
    "flow", "lagi flow", "in the flow", "ritme pas", "ritme terjaga",
    "alur pas", "konsisten", "konsisten banget", "steady", "on track",
    "kelancaran", "smooth", "meluncur mulus", "mulus", "mulus banget",
    "alurnya dapet", "ritmenya dapet", "fokus terjaga", "fokus stabil", "pelan tapi pasti",
    "progres jalan", "jalan terus", "mengalir", "mengalir aja", "teratur jalannya",
    "ritme santai", "tempo pas", "tempo teratur", "selangkah demi selangkah", "step by step",
    "satu-satu", "fokus tertata", "ritme terjaga baik", "ritme konsisten", "progres konsisten",
    "bertahap", "lancar jaya", "lancar banget", "ga kendor ga ngebut", "ritme ideal",
    "beres", "keatasi", "terkendali", "sesuai target", "sesuai rencana",
    "SOP banget", "sesuai jalurnya", "kepegang", "kekontrol", "teratasi",
    "aman jaya", "aman terkendali", "progres oke", "progres bagus", "sesuai ekspektasi",
    "cukup", "cukup banget", "sesuai pacing", "tidak kedistrak", "tidak kewalahan",
    "aman-aman aja", "serba pas", "sesuai jadwal", "on schedule", "teratur jalannya",
    "terkontrol", "aman sentosa", "teratasi dengan baik", "beres satu-satu", "tuntas berurutan",
    "aman banget ini", "oke banget alurnya", "target dapet", "pas sesuai porsi", "sesuai porsinya",
    "terkondusifkan", "dapet alurnya", "bisa diatasi", "bisa diatur", "aman terkontrol",
    "mindful", "kesadaran penuh", "sadar fokus", "paham ritme", "tau batas",
    "bisa ngatur waktu", "manajemen waktu oke", "terkontrol baik", "fokus terarah", "teratur fokusnya",
    "ga overwhelmed", "ga capek-capek amat", "ga pusing-pusing amat", "terukur", "terukur jalannya",
    "langkah terukur", "seimbang posisinya", "stabil ritmenya", "tidak lebay", "sedang-sedang aja",
    "santai tapi dapet", "tenang tapi pasti", "enjoy belajar", "rileks aja", "pikiran adem",
    "ga tertekan", "bebas tekanan", "terkontrol penuh", "fokus yang sehat", "ritme sehat",
    "pola belajar oke", "pola sehat", "belajar sehat", "adem pikiran", "santai tapi produktif",
    "seimbang semuanya", "terkendali dengan baik", "terencana baik", "sesuai flow", "aman damai",
    "chill", "chill banget", "santuy", "santuy abis", "adem ayem",
    "aman bray", "aman bestie", "aman gaes", "smooth bet", "smooth parah",
    "flow banget", "in flow bgt", "on point", "vibes-nya adem", "ritme gaul",
    "aman tentram", "adem tentram", "santuy tapi beres", "wkwk santai aja", "enjoy cuy",
    "chill aja", "santuy dulu", "santuy tapi dapet", "aman aja", "slow tapi pasti",
    "slow motion tapi dapet", "rileks cuy", "teratur bet", "santai bestie", "aman sentosa",
    "ga perlu panik", "ga usah terburu", "jalani aja", "ngalir aja", "ngalir pelan",
    "selow", "selow banget", "selow tapi beres", "ritme juara", "zen mode"
  ],
  vibe: 'Ritme teratur, pikiran tenang, siap melanjutkan alur kerja yang berkelanjutan.',
}
