import type { VocabularyItem } from './types'

export const DISTRACTED_VOCAB: VocabularyItem = {
  label: 'Terganggu / Distraksi / Prokrastinasi',
  moodKey: 'Distracted',
  keywords: [
    "gak fokus", "gak fokus banget", "ga fokus", "kurang fokus", "hilang fokus",
    "buyar", "buyar banget", "fokus buyar", "pikiran buyar", "melayang",
    "pikiran melayang", "melamun", "ngelamun", "ngelamun terus", "kepikiran hal lain",
    "ga bisa konsen", "susah konsen", "konsen buyar", "out of focus", "ga fokus poll",
    "ga fokus parah", "kepikiran yang lain", "kepikiran sana sini", "otak kemana-mana", "kemana-mana pikirannya",
    "ga nyambung", "agak lost", "lost fokus", "gagal fokus", "gak bs konsen",
    "konsentrasi buyar", "konsentrasi pecah", "pecah fokus", "terbagi fokus", "terpecah fokus",
    "melenceng", "agak ngelamun", "suka ngelamun", "pikiran cabang", "fokus cabang",
    "kedistrak", "ke-distrak", "kedistract", "ke-distract", "distrak",
    "distraksi", "kena distraksi", "kebuka sosmed", "keasyikan main HP", "main HP terus",
    "scroll TikTok", "scroll TikTok mulu", "scroll IG", "scroll IG terus", "lihat Reels",
    "lihat Shorts", "scroll X", "scroll Twitter", "keasyikan scroll", "kebuka YouTube",
    "nonton YouTube dulu", "kebuka game", "main game dulu", "ngegame", "keasyikan ngegame",
    "kebuka WA", "reply chat terus", "balasin chat", "liat notif", "ke-distrak notif",
    "notif HP", "liat olshop", "keranjang olshop", "racun olshop", "nonton drakor",
    "nonton anime", "kebuka drama", "keasyikan nonton", "kecanduan HP", "megang HP terus",
    "nunda", "nunda-nunda", "nunda terus", "suka nunda", "ntar-ntaran",
    "entar dulu", "ntar aja", "mampir dulu", "mampir sosmed", "loncat-loncat",
    "loncat materi", "ganti-ganti topik", "pindah-pindah", "ga selese-selese", "muter-muter aja",
    "muter sana sini", "keluar jalur", "off track", "ngelenceng", "asal liat",
    "sekilas doang", "ga tuntas", "ga selesai-selesai", "setengah-setengah", "ngulur waktu",
    "ulur waktu", "buang waktu", "kebuang waktunya", "buang-buang waktu", "distracted poll",
    "ga tahan godaan", "tergoda HP", "tergoda sosmed", "kedistrak materi lain", "mau kerjain yang lain",
    "kepo hal lain", "kepo materi lain", "ngerjain yang lain", "pindah tab terus", "tab kebanyakan",
    "gelisah", "ga bisa diem", "ga betah", "ga betah duduk", "gak betah belajar",
    "risih", "resah", "gatal tangan pengen HP", "pengen megang HP", "gak tahan godaan sosmed",
    "multitasking gagal", "sok multitasking", "split focus", "fokus bocor", "bocor fokusnya",
    "ke-distrak suara", "ke-distrak lingkungan", "berisik", "gak kondusif", "ramai",
    "berisik banget", "ga tenang belajar", "gampang kepancing", "gampang kebawa", "gampang teralih",
    "teralihkan", "gampang teralihkan", "teralihkan terus", "aduh gak fokus", "waduh buyar",
    "yah kedistrak", "waduh ke-distrak", "keasikkan", "kelepasan", "kebablasan",
    "kebablasan scroll", "kebablasan nonton", "kebablasan main", "kebablasan nunda", "kebablasan waktu",
    "salfok", "salah fokus", "salfok banget", "kedistrak parah", "ke-distract bgt",
    "otak kemana-mana", "otak ngelantur", "ngelantur", "ngelantur banget", "oot",
    "out of topic", "salfok abis", "wkwk kedistrak", "wkwk gak fokus", "aduh salfok",
    "yah buyar", "jajan terus", "jajan sosmed", "doomscrolling", "doom scrolling",
    "scroll tanpa arah", "ngelamun jomlo", "ngelamun kosong", "jiwa melayang", "raga di sini jiwa di luar",
    "mager tapi scroll", "rebahan sambil scroll", "jari otomatis scroll", "refleks megang HP", "refleks buka IG",
    "refleks buka TikTok", "ke-distrak mulu", "kacau fokusnya", "hancur fokusnya", "ilang arah",
    "linglung fokus", "kehabisan fokus", "fokus kendor", "kendor fokusnya", "auto kedistrak"
  ],
  vibe: 'Perhatian buyar oleh lingkungan atau gadget, butuh jangkar fokus 1 hal saja dan trik minim distraksi.',
}
