import type { VocabularyItem } from './types'

export const ENERGETIC_VOCAB: VocabularyItem = {
  label: 'Bersemangat / Siap Lanjut',
  moodKey: 'Energetic',
  keywords: [
    "semangat", "semangat banget", "semangat poll", "semangat 45", "full semangat",
    "lagi semangat", "super semangat", "hype", "lagi hype", "hype banget",
    "hype abis", "on fire", "lagi on fire", "menyala", "menyala banget",
    "membara", "berapi-api", "antusias", "antusias banget", "excited",
    "excited banget", "excited poll", "happy", "happy banget", "seneng banget",
    "senang poll", "ceria", "ceria banget", "mood bagus", "mood on",
    "mood naik", "vibe positif", "vibes bagus", "energi positif", "auranya positif",
    "gembira", "girang", "sumringah", "berbinar", "menggebu-gebu",
    "gas", "gass", "gaskeun", "gasskeun", "gaspol",
    "gas terus", "gas lagi", "gass lagi", "let's go", "lets gooo",
    "ayo go", "cuss", "cusss", "sikat", "sikat terus",
    "sikat abis", "hajar", "hajar terus", "bantai", "bantai terus",
    "libas", "libas abis", "babat", "babat abis", "sat set",
    "satset", "sat set sat set", "gercep", "gercep banget", "cekatan",
    "gesit", "lincah", "kebut", "ngebut", "tancap gas",
    "ngegas", "push", "push terus", "lanjut", "lanjut terus",
    "segar", "seger", "seger banget", "seger poll", "fresh",
    "fresh banget", "fit", "fit banget", "bugar", "prima",
    "prima banget", "bertenaga", "bertenaga banget", "full power", "full energi",
    "energi full", "energi meluap", "tenaga full", "nggak capek", "nggak ngantuk",
    "nggak lelah", "nggak loyo", "nggak lemes", "nggak mager", "anti mager",
    "mager hilang", "melek", "melek banget", "melek poll", "terjaga",
    "fokus", "fokus banget", "fokus poll", "konsen", "konsen banget",
    "konsentrasi tinggi", "otak encer", "otak nyala", "pikiran jernih", "pikiran fresh",
    "siap", "siap banget", "siap tempur", "siap gas", "siap sikat",
    "ready", "ready banget", "pengen belajar", "pengen lanjut", "mau lanjut",
    "mau lanjut lagi", "lanjut lagi yuk", "ayo lanjut", "yuk lanjut", "pengen ngejar",
    "kejar target", "kejar materi", "ambis", "ambis banget", "ambis mode on",
    "produktif", "produktif banget", "produktif poll", "rajin", "rajin banget",
    "giat", "giat banget", "inisiatif", "proaktif", "penasaran",
    "penasaran banget", "kepo", "kepo banget", "pengen tau banyak", "pengen eksplor",
    "tantang", "tantang dong", "kasih tantangan", "level up", "naik level",
    "gokil", "gokil banget", "gila energinya", "keren", "keren banget",
    "mantap", "mantap banget", "mantul", "mantul banget", "jos",
    "jos banget", "jos gandos", "gacor", "gacor banget", "ngacir",
    "wus wus", "ngebut wus", "asik", "asik banget", "seru",
    "seru banget", "nagih", "nagih banget", "candu belajar", "bikin nagih",
    "yey", "yeay", "yuhuu", "wuhuu", "wow",
    "woooow", "hahaha semangat", "hihihi gas", "gg", "op",
    "beast mode", "mode on", "mode ngegas", "nggak bisa diem", "nggak sabar"
  ],
  vibe: 'Tinggi energi atau baru selesai istirahat dan siap aksi, butuh partner yang antusias dan langsung mengajak fokus.',
}
