import type { VocabularyItem } from './types'

export const OVERWHELMED_VOCAB: VocabularyItem = {
  label: 'Kewalahan / Terbebani / Panik',
  moodKey: 'Overwhelmed',
  keywords: [
    "pusing", "pusing banget", "pusing poll", "mumet", "mumet banget",
    "bingung", "bingung banget", "bingung parah", "pening", "pening banget",
    "kepala mau pecah", "mau pecah rasanya", "mual mikirin", "blank", "otak blank",
    "ngstuck", "buntu", "buntu banget", "linglung", "lost",
    "ngerasa lost", "gelap banget", "ga tau mau mulai mana", "mau mulai dari mana", "serba salah",
    "ga paham apa-apa", "makin bingung", "nambah bingung", "muter-muter", "ruwet",
    "ruwet banget", "ribet", "ribet banget", "kompleks banget", "pusing mikirin",
    "pusing lihatnya", "mumet parah", "bikin pusing", "bikin mumet", "mumet dah",
    "cemas", "cemas banget", "panik", "panik banget", "panik poll",
    "deg-degan", "was-was", "stres", "stres banget", "stres parah",
    "overthinking", "mikir berlebihan", "takut", "takut banget", "takut ga kelar",
    "takut ga lulus", "takut gagal", "takut telat", "takut ga keburu", "keburu deadline",
    "kepikiran terus", "kepikiran parah", "ga tenang", "kepikiran", "tertekan",
    "tertekan banget", "ngerasa tertekan", "parno", "parno banget", "serem banget",
    "bayangan buruk", "panik anjir", "aduh panik", "astaga cemas", "kaget liat materi",
    "syok liat tugas", "gelisah", "gelisah banget", "ga bisa tidur mikirin", "cemas parah",
    "kewalahan", "kewalahan banget", "numpuk", "tugas numpuk", "numpuk banget",
    "nimbun", "keteteran", "keteteran banget", "ga keburu", "ga kekejar",
    "kejar-kejaran", "dikejar deadline", "deadline mepet", "mepet banget", "overload",
    "cognitive overload", "beban", "beban banget", "keberatan", "banyak banget",
    "kebanyakan", "terlalu banyak", "banjir tugas", "tumpukan materi", "tebel banget",
    "ga habis-habis", "ga ada habisnya", "makin banyak", "berantakan", "kacau",
    "keos", "chaos", "chaos banget", "tumpuk-tumpuk", "dikejar waktu",
    "kehabisan waktu", "sisa waktu dikit", "waktu mepet", "kehabisan cara", "banjir deadline",
    "gak sanggup", "gak mampu", "ga kuat", "ga kuat lagi", "mau nangis",
    "pengen nangis", "nangis banget", "pasrah", "mau menyerah", "pengen nyerah",
    "berat banget", "berat parah", "ga sanggup lagi", "ga sanggup mikir", "putus asa",
    "hopeless", "ga ada harapan", "lelah mental", "lelah batin", "lelah pikiran",
    "capek mikir", "capek banget mikir", "krisis", "mau nyerah aja", "tolongin",
    "butuh bantuan", "beneran bingung", "desperate", "desperate banget", "ga nutut",
    "ga nutut waktunya", "kepepet", "kepepet banget", "bener-bener berat", "ga ketolong",
    "mentok", "mentok banget", "ga tau lagi", "nyerah deh", "lambaikan tangan",
    "nangis batin", "mau meledak", "mau meledak rasanya", "rontok", "otak rontok",
    "benang kusut", "kek benang kusut", "kecekik deadline", "kecekik tugas", "amsyong",
    "ancur", "ancur banget", "remuk", "remuk pikiran", "auto pusing",
    "auto mumet", "auto menangis", "helpp", "helppp", "help me",
    "bengep", "bengep mikir", "mabok materi", "mabok tugas", "pingsan aja deh",
    "skip dulu deh pusing", "aduhh pusing", "yahh numpuk", "wkwk mau nyerah", "wkwk pusing banget",
    "nangis di pojokan", "capek batin", "overload parah", "puyeng", "puyeng banget",
    "ngos-ngosan mikir", "mau pingsan", "ampun dah", "ga sanggup gaes", "kiamat kecil"
  ],
  vibe: 'Kognitif overload, panik, butuh de-eskalasi segera, jangan dijejali saran panjang, perkecil tugas jadi 1 hal mikro.',
}
