import type { VocabularyItem } from './types'

export const TIRED_VOCAB: VocabularyItem = {
  label: 'Lelah / Lemas / Habis Energi',
  moodKey: 'Tired',
  keywords: [
    "capek", "capek banget", "capek poll", "capek parah", "capek bet",
    "capek bener", "lelah", "lelah banget", "lelah poll", "lemes",
    "lemes banget", "lemes poll", "loyo", "loyo banget", "lunglai",
    "pegel", "pegel banget", "pegal", "badan pegal", "badan remuk",
    "sakit badan", "nyeri badan", "kepala berat", "punggung pegel", "mata berat",
    "mata perih", "mata pedes", "ngilu", "ngilu badan", "letih",
    "letih banget", "lesu", "lesu banget", "drop", "drop banget",
    "tumbang", "mau tumbang", "ambruk", "ambruk banget", "letih lesu",
    "ngantuk", "ngantuk banget", "ngantuk poll", "ngantuk berat", "ngantuk parah",
    "ngantuk berat poll", "mata ngantuk", "mata berat banget", "mata mau merem", "mata 5 watt",
    "mata sepet", "kelopak berat", "pengen tidur", "pengen tidur banget", "pengen merem",
    "pengen rebahan", "butuh tidur", "kurang tidur", "kurang tidur banget", "begadang",
    "begadang semalaman", "gadang", "nggak tidur", "susah melek", "nggak bisa melek",
    "ngantuk terus", "bawaannya ngantuk", "ngantuk mulu", "nguap terus", "nguap mulu",
    "ngantuk-ngantuk", "ngantuk cuy", "ngantuk gaes", "mata ngantuk poll", "pengen bobo",
    "mau bobo", "mau tidur aja", "ketiduran", "hampir ketiduran", "ngantuk abis",
    "mager", "mager banget", "mager poll", "mager parah", "males",
    "males banget", "males poll", "males gerak", "males ngapa-ngapain", "lowbat",
    "lowbat banget", "baterai habis", "batre low", "batre habis", "habis baterai",
    "low energy", "low energi", "energi habis", "tenaga habis", "kehabisan energi",
    "ngedrop", "ngedrop banget", "nge-down", "down banget", "lemes bestie",
    "nggak ada tenaga", "nggak ada energi", "nggak bertenaga", "loyo poll", "rebahan aja",
    "pengen rebahan terus", "rebahan mulu", "goleran", "goleran aja", "gak mood gerak",
    "males mikir", "otak lowbat", "mode hemat energi", "mode low power", "nggak kuat ngapa-ngapain",
    "burnout", "burnout banget", "burnout parah", "jenuh", "jenuh banget",
    "bosen", "bosen banget", "bosen poll", "bosan belajar", "jenuh belajar",
    "capek mental", "lelah mental", "capek batin", "lelah batin", "mental capek",
    "mental lelah", "pikiran capek", "otak capek", "otak lelah", "otak penuh",
    "kepala penuh", "kepala capek", "mumet capek", "capek mikir", "capek hati",
    "capek jiwa", "exhausted", "drained", "drained banget", "empty",
    "kosong", "hampa", "ngerasa kosong", "ngerasa hampa", "butuh break",
    "butuh istirahat", "butuh jeda", "butuh recharge", "pengen healing", "butuh healing",
    "tepar", "tepar banget", "tepar poll", "KO", "KO banget",
    "teler", "teler banget", "ambyar", "capek ambyar", "letoy",
    "letoy banget", "nglokro", "loyo gaes", "koid", "mau koid",
    "tipis", "baterai tipis", "sisa 1%", "sisa 5%", "ngos-ngosan",
    "ngos-ngosan banget", "megap-megap", "gak kuat bestie", "capek cuy", "ngantuk cuy",
    "wkwk capek", "aduh capek", "duh capek banget", "ya ampun capek", "ya Allah capek",
    "lemes cuy", "auto rebahan", "auto tidur", "auto pules", "pengen pules",
    "pules aja", "zzz", "ngantuk zzz", "mode zombie", "jadi zombie"
  ],
  vibe: 'Baterai habis, butuh kelembutan tanpa rasa bersalah (anti-guilt), dukung jeda santai/minum/stretching.',
}
